name = "DiffEqNoiseProcess"
uuid = "77a26b50-5914-5dd7-bc55-306e6241c503"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "5.14.2"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PoissonRandom = "e409e4f3-bfea-5376-8464-e040bb5c01ab"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Random123 = "74087812-796a-5b5d-8853-05524746bad3"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
ResettableStacks = "ae5879a3-cd67-5da8-be7f-38c6eb64a37b"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DiffEqBase = "6.11"
Distributions = "0.22, 0.23, 0.24, 0.25"
GPUArraysCore = "0.1"
Optim = "1"
PoissonRandom = "0.4"
QuadGK = "2"
Random123 = "1.2"
RandomNumbers = "1.3"
RecipesBase = "0.7, 0.8, 1.0"
RecursiveArrayTools = "2"
ResettableStacks = "0.6, 1.0"
SciMLBase = "1"
StaticArrays = "0.10, 0.11, 0.12, 1.0"
julia = "1.6"

[extras]
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
SDEProblemLibrary = "c72e72a9-a271-4b2b-8966-303ed956772e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StochasticDiffEq = "789caeaf-c7a9-5a7d-9973-96adeb23e2a0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SDEProblemLibrary", "StatsBase", "StaticArrays", "StochasticDiffEq", "Distributions", "HypothesisTests", "Cubature", "RandomNumbers"]
